export const userConstants={
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST',
}

export const registerConstants = {
    REGISTER_REQUEST:'REGISTER_REQUEST',
    REGISTER_FAILURE:'REGISTER_FAILURE',
    REGISTER_SUCCESS:'REGISTER_SUCCESS',  
}

export const categoryConstants = {
    GET_ALL_CATEGORIES_REQUEST: 'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_SUCCESS:'GET_ALL_CATEGORIES_SUCCESS',
    GET_ALL_CATEGORIES_FAILURE:'GET_ALL_CATEGORIES_FAILURE'
}

export const initialDataConstant = {
    GET_INITIAL_DATA_REQUEST:'GET_INITIAL_DATA_REQUEST',
    GET_INITIAL_DATA_SUCCESS:'GET_INITIAL_DATA_SUCCESS',
    GET_INITIAL_DATA_FAILURE:'GET_INITIAL_DATA_FAILURE'

}

export const productConstants = {
    PRODUCTS_REQUEST:'PRODUCTS_REQUEST',
    PRODUCTS_SUCCESS:'PRODUCTS_SUCCESS',
    CREATE_PRODUCTS_SUCCESS:'PRODUCTS_SUCCESS',
    PRODUCTS_FAILURE:'PRODUCTS_FAILURE'
}

export const totalUsersConstants = {
    TOTAL_USER_REQUEST:'TOTAL_USER_REQUEST',
    TOTAL_USER_SUCCESS:'TOTAL_USER_SUCCESS',
    TOTAL_USER_FAILURE:'TOTAL_USER_FAILURE',
}

export const sellersConstants = {
    SELLERS_REQUEST: 'SELLERS_REQUEST',
    SELLERS_SUCCESS: 'SELLERS_SUCCESS',
    SELLERS_FAILURE: 'SELLERS_FAILURE',
}

export const enquiryConstants = {
    ENQUIRY_REQUEST: 'ENQUIRY_REQUEST',
    ENQUIRY_SUCCESS: 'ENQUIRY_SUCCESS',
    ENQUIRY_FAILURE: 'ENQUIRY_FAILURE',
}

export const searchConstants = {
    SEARCH_REQUEST: 'SEARCH_REQUEST',
    SEARCH_SUCCESS: 'SEARCH_SUCCESS',
    SEARCH_FAILURE: 'SEARCH_FAILURE',
}


export const otpConstants = {
    OTP_REQUEST: 'OTP_REQUEST',
    OTP_SUCCESS: 'OTP_SUCCESS',
    OTP_FAILURE: 'OTP_FAILURE',
}